"""second

Revision ID: 569b4e414768
Revises: 715355f9572e
Create Date: 2022-12-11 14:21:11.187431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569b4e414768'
down_revision = '715355f9572e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microblog_posts', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'microblog_posts', 'microblog_posts', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'microblog_posts', type_='foreignkey')
    op.drop_column('microblog_posts', 'parent_id')
    # ### end Alembic commands ###
