"""second 2

Revision ID: 65f6862e1b76
Revises: 569b4e414768
Create Date: 2022-12-11 14:23:25.287532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f6862e1b76'
down_revision = '569b4e414768'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
