"""second 3

Revision ID: c4fc4a1a7026
Revises: 65f6862e1b76
Create Date: 2022-12-11 15:14:58.947723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fc4a1a7026'
down_revision = '65f6862e1b76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
